-- ==========================================================================
--  RAZENLAB · estrutura do banco (Supabase)
--  Cole tudo no SQL Editor do Supabase e clique em RUN.
--  Pode rodar de novo sem perder dados: tudo usa "if not exists".
-- ==========================================================================

create extension if not exists pgcrypto;

-- --------------------------------------------------------------------------
-- 1. QUEM ADMINISTRA
--    Só usuários listados aqui entram no painel e enxergam pedidos.
-- --------------------------------------------------------------------------
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- --------------------------------------------------------------------------
-- 2. TABELAS
--    Os detalhes de cada registro ficam em "dados" (jsonb), no mesmo formato
--    que o painel já usa. Assim dá para acrescentar campos sem mexer no banco.
-- --------------------------------------------------------------------------
create table if not exists public.config (          -- custos, Pix e dados privados
  id int primary key default 1 check (id = 1),
  dados jsonb not null default '{}'::jsonb,
  atualizado_em timestamptz not null default now()
);

create table if not exists public.site (            -- o que o site público mostra
  id int primary key default 1 check (id = 1),
  dados jsonb not null default '{}'::jsonb,
  atualizado_em timestamptz not null default now()
);

create table if not exists public.filamentos (
  id uuid primary key default gen_random_uuid(),
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  token uuid not null default gen_random_uuid() unique,   -- link secreto do cliente
  status text not null default 'solicitado'
    check (status in ('solicitado','orcamento','comprovante','pago','imprimindo','pronto','enviado','entregue','cancelado','perdido')),
  cliente text,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index if not exists pedidos_status_idx on public.pedidos (status);

-- situação "perdido" = orçamento que o cliente não fechou (atualiza também bancos já criados)
alter table public.pedidos drop constraint if exists pedidos_status_check;
alter table public.pedidos add constraint pedidos_status_check
  check (status in ('solicitado','orcamento','comprovante','pago','imprimindo','pronto','enviado','entregue','cancelado','perdido'));
create index if not exists pedidos_criado_idx on public.pedidos (criado_em desc);

create table if not exists public.vitrine (
  id uuid primary key default gen_random_uuid(),
  visivel boolean not null default true,
  destaque boolean not null default false,
  dados jsonb not null default '{}'::jsonb,
  fotos text[] not null default '{}',
  criado_em timestamptz not null default now()
);

insert into public.config (id) values (1) on conflict (id) do nothing;
insert into public.site (id, dados) values (1, '{"nome":"RazenLab"}') on conflict (id) do nothing;

create or replace function public.tocar() returns trigger language plpgsql as $$
begin new.atualizado_em = now(); return new; end $$;

drop trigger if exists pedidos_tocar on public.pedidos;
create trigger pedidos_tocar before update on public.pedidos for each row execute function public.tocar();
drop trigger if exists config_tocar on public.config;
create trigger config_tocar before update on public.config for each row execute function public.tocar();
drop trigger if exists site_tocar on public.site;
create trigger site_tocar before update on public.site for each row execute function public.tocar();

-- --------------------------------------------------------------------------
-- 3. SEGURANÇA (RLS)
--    Visitante: lê o site e a vitrine visível. Nada mais.
--    Admin: lê e grava tudo.
--    Cliente: só vê o próprio pedido, pelas funções da seção 4.
-- --------------------------------------------------------------------------
alter table public.admins     enable row level security;
alter table public.config     enable row level security;
alter table public.site       enable row level security;
alter table public.filamentos enable row level security;
alter table public.pedidos    enable row level security;
alter table public.vitrine    enable row level security;

drop policy if exists "admin se ve" on public.admins;
create policy "admin se ve" on public.admins for select to authenticated using (user_id = auth.uid());

drop policy if exists "admin tudo" on public.config;
create policy "admin tudo" on public.config for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin tudo" on public.filamentos;
create policy "admin tudo" on public.filamentos for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin tudo" on public.pedidos;
create policy "admin tudo" on public.pedidos for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "todos leem" on public.site;
create policy "todos leem" on public.site for select to anon, authenticated using (true);
drop policy if exists "admin edita" on public.site;
create policy "admin edita" on public.site for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "todos veem visiveis" on public.vitrine;
create policy "todos veem visiveis" on public.vitrine for select to anon, authenticated using (visivel or public.is_admin());
drop policy if exists "admin edita" on public.vitrine;
create policy "admin edita" on public.vitrine for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- HISTÓRICO: cada mudança de situação fica registrada sozinha, com data e hora.
-- É o que permite analisar depois quanto tempo cada orçamento levou para fechar.
create table if not exists public.pedidos_historico (
  id bigint generated always as identity primary key,
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  de text,
  para text not null,
  quem uuid default auth.uid(),
  em timestamptz not null default now()
);
create index if not exists pedidos_historico_pedido_idx on public.pedidos_historico (pedido_id, em);
alter table public.pedidos_historico enable row level security;
drop policy if exists "admin le historico" on public.pedidos_historico;
create policy "admin le historico" on public.pedidos_historico for select to authenticated using (public.is_admin());

create or replace function public.registrar_status() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.pedidos_historico (pedido_id, de, para) values (new.id, null, new.status);
  elsif new.status is distinct from old.status then
    insert into public.pedidos_historico (pedido_id, de, para) values (new.id, old.status, new.status);
  end if;
  return new;
end $$;
drop trigger if exists pedidos_historico_trg on public.pedidos;
create trigger pedidos_historico_trg after insert or update of status on public.pedidos
  for each row execute function public.registrar_status();

-- pedidos que já existiam ganham um primeiro registro, com a data em que foram criados
insert into public.pedidos_historico (pedido_id, de, para, em, quem)
select p.id, null, p.status, p.criado_em, null from public.pedidos p
where not exists (select 1 from public.pedidos_historico h where h.pedido_id = p.id);

grant select on public.site, public.vitrine to anon;
grant select on public.pedidos_historico to authenticated;
grant select, insert, update, delete on public.config, public.site, public.filamentos, public.pedidos, public.vitrine, public.admins to authenticated;

-- --------------------------------------------------------------------------
-- 4. FUNÇÕES QUE O SITE DO CLIENTE PODE CHAMAR
-- --------------------------------------------------------------------------

-- Cliente pede um orçamento pelo site
create or replace function public.solicitar_orcamento(
  p_nome text, p_contato text, p_email text, p_descricao text, p_qtd int,
  p_quando text, p_cep text, p_endereco jsonb, p_anexo text
) returns json
language plpgsql security definer set search_path = public as $$
declare
  r public.pedidos;
  v_qtd int := greatest(1, least(coalesce(p_qtd, 1), 10000));
begin
  if length(trim(coalesce(p_nome, ''))) < 2 then raise exception 'Informe seu nome.'; end if;
  if length(trim(coalesce(p_descricao, ''))) < 3 then raise exception 'Descreva o que você precisa.'; end if;
  if length(regexp_replace(coalesce(p_contato, ''), '\D', '', 'g')) < 10 then raise exception 'Informe um WhatsApp com DDD.'; end if;
  if length(p_nome) > 120 or length(p_descricao) > 3000 or length(coalesce(p_email, '')) > 160
     or length(coalesce(p_endereco::text, '')) > 1500 or length(coalesce(p_anexo, '')) > 300 then
    raise exception 'Algum campo ficou longo demais.';
  end if;
  -- trava simples contra abuso: até 5 pedidos por telefone em 24 h
  if (select count(*) from public.pedidos
      where regexp_replace(coalesce(dados->>'contato', ''), '\D', '', 'g') = regexp_replace(p_contato, '\D', '', 'g')
        and criado_em > now() - interval '1 day') >= 5 then
    raise exception 'Muitas solicitações hoje com este telefone. Fale direto pelo WhatsApp.';
  end if;

  insert into public.pedidos (status, cliente, dados) values ('solicitado', trim(p_nome), jsonb_build_object(
    'cliente', trim(p_nome),
    'contato', trim(p_contato),
    'email', nullif(trim(coalesce(p_email, '')), ''),
    'pedidoCliente', trim(p_descricao),
    'quando', left(coalesce(p_quando, ''), 120),
    'cep', left(coalesce(p_cep, ''), 9),
    'endereco', coalesce(p_endereco, '{}'::jsonb),
    'anexo', nullif(p_anexo, ''),
    'peca', left(trim(p_descricao), 60),
    'qtd', v_qtd,
    'origem', 'site'
  )) returning * into r;

  return json_build_object('numero', r.numero, 'token', r.token);
end $$;

-- Cliente abre o próprio pedido pelo link secreto
create or replace function public.ver_pedido(p_token uuid) returns json
language plpgsql stable security definer set search_path = public as $$
declare
  r public.pedidos;
  n jsonb;
  com_preco boolean;
  v_validade date;
  v_vencido boolean;
begin
  select * into r from public.pedidos where token = p_token;
  if not found then return null; end if;
  select coalesce(dados->'negocio', '{}'::jsonb) into n from public.config where id = 1;
  com_preco := r.status not in ('solicitado', 'cancelado', 'perdido');
  v_validade := case when (r.dados->>'validadeAte') ~ '^\d{4}-\d{2}-\d{2}$' then (r.dados->>'validadeAte')::date end;
  v_vencido := r.status = 'orcamento' and v_validade is not null and v_validade < current_date;

  return json_build_object(
    'numero', r.numero,
    'status', r.status,
    'criado_em', r.criado_em,
    'atualizado_em', r.atualizado_em,
    'cliente', r.dados->>'cliente',
    'pedidoCliente', r.dados->>'pedidoCliente',
    'peca', r.dados->>'peca',
    'material', r.dados->>'materialTexto',
    'qtd', r.dados->'qtd',
    'precoUn', case when com_preco then r.dados->'precoUn' end,
    'desconto', case when com_preco then r.dados->'desconto' end,
    'frete', case when com_preco then r.dados->'entrega' end,
    'freteServico', case when com_preco then r.dados->>'freteServico' end,
    'total', case when com_preco then r.dados->'total' end,
    'prazo', r.dados->>'prazo',
    'recado', r.dados->>'recado',
    'rastreio', r.dados->>'rastreio',
    'cep', r.dados->>'cep',
    'endereco', r.dados->'endereco',
    'comprovante', (r.dados->>'comprovante') is not null,
    'validadeAte', v_validade,
    'vencido', v_vencido,
    'validadeDias', n->'validadeDias',
    'whatsapp', n->>'whatsapp',
    'pix', case when r.status in ('orcamento', 'comprovante') and not v_vencido then json_build_object(
      'chave', n->>'pixChave', 'nome', n->>'pixNome', 'cidade', n->>'pixCidade') end
  );
end $$;

-- Cliente avisa que pagou e anexa o comprovante
create or replace function public.enviar_comprovante(p_token uuid, p_arquivo text) returns json
language plpgsql security definer set search_path = public as $$
declare r public.pedidos;
begin
  select * into r from public.pedidos where token = p_token for update;
  if not found then raise exception 'Pedido não encontrado.'; end if;
  if r.status not in ('orcamento', 'comprovante') then raise exception 'Este pedido não está aguardando pagamento.'; end if;
  if p_arquivo is null or p_arquivo !~ '^comprovantes/[A-Za-z0-9_-]{1,80}\.(jpg|jpeg|png|webp|pdf)$' then raise exception 'Arquivo inválido.'; end if;

  update public.pedidos
     set status = 'comprovante',
         dados = dados || jsonb_build_object('comprovante', p_arquivo, 'comprovanteEm', now())
   where id = r.id;
  return json_build_object('ok', true);
end $$;

-- Painel: depois de importar pedidos antigos, continua a numeração do maior
create or replace function public.admin_ajustar_numeracao() returns bigint
language plpgsql security definer set search_path = public as $$
declare m bigint;
begin
  if not public.is_admin() then raise exception 'Sem permissão.'; end if;
  select coalesce(max(numero), 0) into m from public.pedidos;
  if m = 0 then
    perform setval(pg_get_serial_sequence('public.pedidos', 'numero'), 1, false);
  else
    perform setval(pg_get_serial_sequence('public.pedidos', 'numero'), m, true);
  end if;
  return m + 1;
end $$;

revoke all on function public.solicitar_orcamento(text,text,text,text,int,text,text,jsonb,text) from public;
revoke all on function public.ver_pedido(uuid) from public;
revoke all on function public.enviar_comprovante(uuid,text) from public;
revoke all on function public.admin_ajustar_numeracao() from public;
grant execute on function public.solicitar_orcamento(text,text,text,text,int,text,text,jsonb,text) to anon, authenticated;
grant execute on function public.ver_pedido(uuid) to anon, authenticated;
grant execute on function public.enviar_comprovante(uuid,text) to anon, authenticated;
grant execute on function public.admin_ajustar_numeracao() to authenticated;
grant execute on function public.is_admin() to anon, authenticated;

-- --------------------------------------------------------------------------
-- 5. ARQUIVOS
--    vitrine       → fotos públicas do site (só você envia)
--    anexos        → fotos/arquivos 3D que o cliente manda (só você abre)
--    comprovantes  → comprovantes de Pix (só você abre)
-- --------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('vitrine', 'vitrine', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('anexos', 'anexos', false, 26214400, null),
  ('comprovantes', 'comprovantes', false, 10485760, array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "razenlab vitrine admin grava" on storage.objects;
create policy "razenlab vitrine admin grava" on storage.objects for insert to authenticated
  with check (bucket_id = 'vitrine' and public.is_admin());
drop policy if exists "razenlab vitrine admin altera" on storage.objects;
create policy "razenlab vitrine admin altera" on storage.objects for update to authenticated
  using (bucket_id = 'vitrine' and public.is_admin());
drop policy if exists "razenlab vitrine admin apaga" on storage.objects;
create policy "razenlab vitrine admin apaga" on storage.objects for delete to authenticated
  using (bucket_id = 'vitrine' and public.is_admin());

-- cliente só consegue ENVIAR; não lista nem baixa nada
drop policy if exists "razenlab clientes enviam" on storage.objects;
create policy "razenlab clientes enviam" on storage.objects for insert to anon, authenticated
  with check (bucket_id in ('anexos', 'comprovantes'));
drop policy if exists "razenlab admin le arquivos" on storage.objects;
create policy "razenlab admin le arquivos" on storage.objects for select to authenticated
  using (bucket_id in ('anexos', 'comprovantes', 'vitrine') and public.is_admin());
drop policy if exists "razenlab admin apaga arquivos" on storage.objects;
create policy "razenlab admin apaga arquivos" on storage.objects for delete to authenticated
  using (bucket_id in ('anexos', 'comprovantes') and public.is_admin());

-- --------------------------------------------------------------------------
-- 6. AVISO EM TEMPO REAL
--    O painel recebe na hora quando chega um pedido novo ou um comprovante.
-- --------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'pedidos') then
    alter publication supabase_realtime add table public.pedidos;
  end if;
end $$;

-- ==========================================================================
--  PRONTO. Próximo passo: o arquivo 02_admin.sql, depois de criar seu usuário.
-- ==========================================================================
